from flask import Flask, render_template, url_for, session, get_template_attribute
from forms import LoginForm
from werkzeug.utils import secure_filename
from flask import request, redirect
import os
import pandas as pd
import numpy as np
import getpass

from flask import send_from_directory

from flask import flash

from forms import LoginForm
from flask_login import login_user, current_user, logout_user, login_required

UPLOAD_FOLDER = '/path/to/the/uploads'





app = Flask(__name__)
app.config['SECRET_KEY'] = "something complex generated by maybe os.urandom"
app.config['IMAGE_UPLOADS'] = "/Users/olyafomicheva/desktop/flask_test/uploads"
app.config["ALLOWED_IMAGE_EXTENSIONS"] = ["CSV","XLS","XLSX"]
app.config['MAX_CONTENT_LENGTH'] = 50 * 1024 * 1024



def allowed_file(filename):

    if not "." in filename:
        return False

    ext = filename.rsplit(".", 1)[1]

    if ext.upper() in app.config["ALLOWED_IMAGE_EXTENSIONS"]:
        return True
    else:
        return False

def check_csv(filename):

    ext = filename.rsplit(".", 1)[1]

    if ext.upper() in ["CSV"]:
        return True
    else:
        return False


def allowed_image_filesize(filesize):

    if int(filesize) <= app.config["MAX_IMAGE_FILESIZE"]:
        return True
    else:
        return False


@app.route("/")
@app.route("/home", methods=["GET", "POST"])
def upload_file():

                         
    return render_template("upload_file.html")




@app.route("/login", methods=['GET', 'POST'])
def login():

    Users = pd.read_csv(os.path.join(app.config["IMAGE_UPLOADS"], 'users.csv'))

    if current_user.is_authenticated:
        return redirect(url_for('home'))
    
    form = LoginForm()
    
    if form.validate_on_submit():
        user = Users[(Users['email']==form.email.data) & (Users['password']==form.password.data)]
        
        if user:
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)




@app.route("/uploader", methods=["GET", "POST"])
def uploader():
    
    
    if request.method == "POST":

        if request.files:

            file = request.files["file"]
            

            if file.filename == '':
               flash('No file selected for uploading')
               return redirect('/')
                        
            if not allowed_file(file.filename):
                    flash('Unsupported file type')
                    return redirect('/')

               
            filename = secure_filename(file.filename)

            path = os.path.join(app.config["IMAGE_UPLOADS"], filename)

            file.save(path)

            session['path'] = path
            session['filename'] = filename

            if not check_csv(filename):
                df2 = pd.read_excel(path,sheetname="Sheet1",index_col=None)
            else:
                df2 = pd.read_csv(path)


            col = list(df2.columns)    
           
            #return send_from_directory('/Users/FOMIOLNY/desktop/flask_test/uploads', filename='xxx.csv', as_attachment=True)
            #return render_template("xx.html",title='ccc', labels=bar_labels, values=bar_values, max=100)
            

            return render_template("upload.html", filename = filename, columns = col)




@app.route("/uploader2", methods=["GET", "POST"])
def uploader2():
    
            path = session.get('path')

            filename = session.get('filename')

            feds = pd.read_csv(os.path.join(app.config["IMAGE_UPLOADS"], 'federations.csv'))



            if not check_csv(filename):
                df2 = pd.read_excel(path,sheetname="Sheet1",index_col=None)
            else:
                df2 = pd.read_csv(path)   


            field = request.form.get('field')    
            

            
            
            return render_template('_test.html', field=field)
            
            



@app.route('/federation_by_size/<string:size>', methods=["GET", "POST"])
def federation_by_size(size):
    #param=request.args
    
    s = size
    
    session['s'] = s


    x = session.get('x')
    bar_labels = session.get('bar_labels')

    m = pd.read_csv(x)
    

    x = m.groupby('City-Size')
    y = x.get_group(size)
    num=y.shape[0]

    return render_template("federation_by_size.html",tables=[y.to_html(classes='table-sticky sticky-enabled', index=False)], fed_sizes=bar_labels,num=num)



@app.route('/federation_by_size_all', methods=["GET", "POST"])
def federation_by_size_all():
    #param=request.args
    
    path = session.get('path')

    filename = session.get('filename')

    feds = pd.read_csv(os.path.join(app.config["IMAGE_UPLOADS"], 'federations.csv'))



    if not check_csv(filename):
        df2 = pd.read_excel(path,sheetname="Sheet1",index_col=None)
    else:
        df2 = pd.read_csv(path)   


    field = request.form.get('field') 

    report = df2.merge(feds, left_on=field, right_on='Community')
   

    
    bar_labels = session.get('bar_labels')

    

    return render_template("federation_by_size_all.html",tables=[report.to_html(classes='table-sticky sticky-enabled',index=False)],fed_sizes=bar_labels)    



@app.route('/analysis', methods=["GET", "POST"])
def analysis():
    

    

    x = session.get('x')
    m=pd.read_csv(x)
    columns=list(m.columns)
    

    #y=pd.DataFrame(m.groupby(g[0])[g[1]].count()).reset_index()
    #y.to_csv(os.path.join(app.config["IMAGE_UPLOADS"], 'xx2.csv'), index=False)

    #return send_from_directory('/Users/FOMIOLNY/desktop/flask_test/uploads', filename='xx2.csv', as_attachment=True)
    #return render_template("xxxxx.html", g=g[0])
    return render_template("analysis.html", columns = columns)


@app.route('/analysis_report', methods=["GET", "POST"])
def analysis_report():
    

    g=request.form.getlist('field')
    gg =request.form.get('select2')

    x = session.get('x')
    m=pd.read_csv(x)
    columns=list(m.columns)
    

    y=pd.DataFrame(m.groupby(g)[gg].count()).reset_index()
    y.to_csv(os.path.join(app.config["IMAGE_UPLOADS"], 'xx5.csv'), index=False)

    filename = session.get('filename')

    #return send_from_directory('/Users/FOMIOLNY/desktop/flask_test/uploads', filename='xx2.csv', as_attachment=True)
    #return render_template("xxxxx.html", g=g[0])
    return render_template("_test.html", tables=[y.to_html(classes='table-sticky sticky-enabled',index=False)])


   

@app.route('/feds', methods=['GET', 'POST'])
def animals():
    selected_animal = request.args.get('type')
    return render_template(animals.html, title='Animal Details', animal=selected_animal)
    

    


@app.route("/download", methods=["GET", "POST"])
def download():

        #if request.method == 'GET':

        filename = session.get('filename')

        s = session.get('s')
        
       
        x = session.get('x')
        m = pd.read_csv(x)
        report = m[m['City-Size']==s]
        report.to_csv(os.path.join(app.config["IMAGE_UPLOADS"], filename.rsplit(".", 1)[0]+"_"+s+"."+filename.rsplit(".", 1)[1]), index=False)

        return send_from_directory(app.config["IMAGE_UPLOADS"], filename=filename.rsplit(".", 1)[0]+"_"+s+"."+filename.rsplit(".", 1)[1], as_attachment=True)
        #return render_template("xxx.html",s=s)
    
             







@app.route("/about")
def about():
    return render_template('about.html', title='About')





if __name__ == '__main__':
    app.run(debug=False)